version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      # HTTP/HTTPS
      - "80:80"
      - "443:443"
      # Mail ports (SMTP / POP3 / IMAP)
      - "25:25"
      - "465:465"
      - "587:587"
      - "110:110"
      - "143:143"
      - "993:993"
      - "995:995"
    volumes:
      # کانفیگ HTTP و Stream
      - ./conf:/etc/nginx/conf.d
      - ./stream_conf:/etc/nginx/stream_conf
      - ./nginx.conf:/etc/nginx/nginx.conf
      # SSL Certificates
      - ./ssl:/etc/nginx/ssl
      # لاگ‌ها
      - ./logs:/etc/nginx/logs
      # فایل‌های HTML
      - ./html:/usr/share/nginx/html
    networks:
      - nginx-network
    restart: unless-stopped

networks:
  nginx-network:
    driver: bridge
