version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf:/etc/nginx/conf.d
      - ./ssl:/etc/nginx/ssl
      #- ./logs:/var/log/nginx
      - ./logs:/etc/nginx/logs  # تغییر مسیر volume mapping
      - ./html:/usr/share/nginx/html
    networks:
      - nginx-network
    restart: unless-stopped

networks:
  nginx-network:
    driver: bridge

